[package]
name    = "vt_ui"
publish = false
version = "0.1.0"

authors.workspace    = true
edition.workspace    = true
license.workspace    = true
repository.workspace = true

[dependencies]
anyhow    = { workspace = true }
crossterm = { workspace = true }
ratatui   = { workspace = true }
