name: "Setup"

description: "Setup Rust tools"

runs:
  using: "composite"
  steps:
    - name: Install cargo-binstall
      uses: cargo-bins/cargo-binstall@b9bf4400702f721d469eec4d280125f650c85638 # v1.12.2

    - name: Restore CI tools
      id: cache-tools-restore
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cargo/bin/just
          ~/.cargo/bin/cargo-shear
        key: cache-tools

    - name: Install cargo-shear
      if: steps.cache-tools-restore.outputs.cache-hit != 'true'
      run: cargo binstall just cargo-shear -y
      shell: bash

    - name: Save CI tools
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
      with:
        path: |
          ~/.cargo/bin/just
          ~/.cargo/bin/cargo-shear
        key: cache-tools
