[package]
name = "vt"
version = "1.3.3"
authors = ["killbasa <contact@shaneb.xyz>"]
edition = "2021"
repository = "https://github.com/killbasa/vt"
license = "MIT"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.81"
chrono = "0.4.37"
chrono-humanize = "0.2.3"
clap = { version = "4.5.4", features = ["derive"] }
clap_complete = "4.5.1"
colored = "2.1.0"
confy = "0.5.1"
const_format = "0.2.32"
once_cell = "1.19.0"
reqwest = { version = "0.11.27", features = ["blocking", "json"] }
roxmltree = "0.19.0"
rpassword = "7.3.1"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
