[package]
name = "vt"
version = "1.1.0"
authors = ["killbasa <contact@shaneb.xyz>"]
edition = "2021"
repository = "https://github.com/killbasa/vt"
license = "MIT"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.79"
chrono = "0.4.33"
chrono-humanize = "0.2.3"
clap = { version = "4.4.18", features = ["derive"] }
clap_complete = "4.4.9"
colored = "2.1.0"
confy = "0.5.1"
const_format = "0.2.32"
once_cell = "1.19.0"
reqwest = { version = "0.11.23", features = ["blocking", "json"] }
roxmltree = "0.19.0"
rpassword = "7.3.1"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.112"
