[package]
authors    = ["killbasa <contact@shaneb.xyz>"]
edition    = "2021"
license    = "MIT"
name       = "vt"
repository = "https://github.com/killbasa/vt"
version    = "1.3.6"

[profile.release]
codegen-units = 1
lto           = true
strip         = "symbols"

[dependencies]
anyhow          = "1.0.88"
chrono          = "0.4.37"
chrono-humanize = "0.2.3"
clap            = { version = "4.5.17", features = ["derive"] }
clap_complete   = "4.5.26"
colored         = "2.1.0"
confy           = "0.5.1"
const_format    = "0.2.33"
once_cell       = "1.20.0"
openssl         = { version = "0.10.66", features = ["vendored"] }
reqwest         = { version = "0.11.27", features = ["blocking", "json"] }
roxmltree       = "0.19.0"
rpassword       = "7.3.1"
serde           = { version = "1.0.210", features = ["derive"] }
serde_json      = "1.0.128"
