[package]
name = "vt"
version = "0.1.0"
authors = ["killbasa <contact@shaneb.xyz>"]
edition = "2021"
repository = "https://github.com/killbasa/vt"
license = "MIT"

[profile.release]
lto = true

[dependencies]
anyhow = "1.0.79"
chrono = "0.4.31"
chrono-humanize = "0.2.3"
clap = { version = "4.4.13", features = ["derive"] }
clap_complete = "4.4.6"
colored = "2.1.0"
confy = "0.5.1"
once_cell = "1.19.0"
reqwest = { version = "0.11.23", features = ["blocking"] }
roxmltree = "0.19.0"
serde = { version = "1.0.194", features = ["derive"] }
serde_json = "1.0.111"
