name: CI

on:
  pull_request:
    paths-ignore:
      - "**/README.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
