name: CI

on:
  pull_request:
    paths-ignore:
      - "**/README.md"

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Install xmllint
        run: sudo apt-get install -y pkg-config libssl-dev

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
